language: "en-US"
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Dont merge"
  drafts: false
chat:
  auto_reply: true
excludes:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  - "**/.next/**"
  - "**/package-lock.json"
  - "**/yarn.lock"
  - "**/*.min.js"
  - "**/*.map"
  - "**/prisma/migrations/**"
  - "**/.git/**"
